version: "3.8"

services:
  ui:
    hostname: ui
    container_name: ui
    build:
      args:
        - NODEJS_VERSION
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - ui-node-modules:/app/node_modules
    # depends_on:
    #   - api

  # api:
  #   hostname: api
  #   container_name: api
  #   depends_on:
  #     - db

  # db:
  #   hostname: db
  #   container_name: db

volumes:
  ui-node-modules:
